---
version: '2'
services:
  db:
    image: mysql
    volumes:
      - ./.data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:      drupal
      MYSQL_USER:          drupal
      MYSQL_PASSWORD:      drupal
  drupal:
    depends_on:
      - db
    image: banderson/drupal
    links:
      - db:drupal_db
    ports:
      - 8084:80
    volumes:
      - ./drupal:/var/www/drupal
