---
version: '2'

services:
  db:
    container_name: purchasing_db
    image: mysql:5.7
    restart: always
    volumes:
      - ./.data:/var/lib/mysql
      - ./drupal.sql:/docker-entrypoint-initdb.d/drupal.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --max-allowed-packet=128M

  search:
    container_name: purchasing_search
    image: reg.hcpss.org/purchasing/search
    build: docker/search
    restart: always
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
    ports:
      - 8983:8983

  drupal:
    container_name: purchasing_web
    image: reg.hcpss.org/purchasing/web:staff_catalog
    restart: always
    depends_on:
      - db
      - search
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    links:
      - db:drupal_db
      - search:search
    ports:
      - 8086:80
    volumes:
      - ./drupal:/var/www/drupal
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      DRUPAL_ENV: ${DRUPAL_ENV}
    command: >
      bash -c "drush --root=/var/www/drupal/web upwd webmaster admin
      && /usr/sbin/apache2ctl -D FOREGROUND"
