---
version: '2'

services:
  db:
    container_name: purchasing_db
    image: mysql:5.7
    volumes:
      - ./.data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --max-allowed-packet=128M

  search:
    container_name: purchasing_search
    build: docker/search
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
    ports:
      - 8983:8983

  drupal:
    container_name: purchasing_web
    depends_on:
      - db
      - search
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    links:
      - db:drupal_db
      - search:search
    ports:
      - 8086:80
    volumes:
      - ./drupal:/var/www/drupal
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOSTNAME: ${MYSQL_HOSTNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
