FROM solr

MAINTAINER brendan_anderson@hcpss.org
LABEL vendor="Howard County Public School System"
LABEL org.hcpss.purchasing.search.version="1.0.0"

COPY --chown=solr:solr config/mycore /opt/solr/server/solr/mycores/mycore
